### ISSUE TITLE
Upgrade rimdev.io to Astro

### ISSUE THREAD

**Issue by hougasian** [ritterim/rimdev-blog#484]
## 🔧 Enhancement Request 

Upgrade to [Astro](https://astro.build/) as a test bed to replace Hugo.

##  Benefits of refactor

Faster builds, moving technology forward.

**Comment by mackenziegates** [comment]
pending vite updates

**Comment by hougasian** [comment]
Successfully deployed https://delightful-wave-0b6a5650f.2.azurestaticapps.net/
A bit wonky; Taking out of this sprint as this is truly a background task.
<img width="1785" alt="Screen Shot 2023-02-15 at 9 23 15 AM" src="https://user-images.githubusercontent.com/6231956/219054087-a1e7c9b3-2531-4df6-bd9a-0bb03e63a5ec.png">

**Comment by mrtrimble** [comment]
This can be closed - the Astro version of rimdev.io is now live

**Comment by hougasian** [comment]
<img src="https://media2.giphy.com/media/qsfU11oONKa6HZWNy9/giphy.gif"/>
